version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cacador_ofertas
    volumes:
      - mysql_data:/var/lib/mysql 

  bot:
    build: .
    restart: always
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: bot_chrome
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  mysql_data: