version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cacador_ofertas
    volumes:
      - mysql_data:/var/lib/mysql 

  instant_bot:
    build: .
    container_name: cacador_telegram
    restart: always
    volumes:
      - .:/app
    command: php /app/daemons/instant-daemon.php
    depends_on:
      - db

  fastest_bot:
    build: .
    container_name: cacador_steam
    restart: always
    volumes:
      - .:/app
    command: php /app/daemons/fastest-daemon.php
    depends_on:
      - db

  fast_bot:
    build: .
    container_name: cacador_reddit
    restart: always
    volumes:
      - .:/app
    command: php /app/daemons/fast-daemon.php
    depends_on:
      - db

  # slow_bot:
  #   build: .
  #   container_name: cacador_lojas
  #   restart: always
  #   volumes:
  #     - .:/app
  #   command: php /app/daemons/slow-daemon.php
  #   depends_on:
  #     - db

volumes:
  mysql_data: